apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetris-frontend
  template:
    metadata:
      labels:
        app: tetris-frontend
    spec:
      containers:
        - name: tetris-frontend
          image: kavinnaik/tetris-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tetris-frontend
spec:
  type: NodePort
  selector:
    app: tetris-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
